# fly.toml app configuration file generated for trivia-chat-app on 2024-02-16T10:30:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trivia-chat-app'
primary_region = 'mia'

[build]

[env]
  FIREBASE_APIKEY= "AIzaSyBI9IxAtUfAVxFcUs1uTbOF86ChtSNypsE"
  FIREBASE_AUTHDOMAIN ="triviachatapp.firebaseapp.com"
  FIREBASE_PROJECTID= "triviachatapp"
  FIREBASE_STORAGEBUCKET= "triviachatapp.appspot.com"
  FIREBASE_MESSAGINGSENDERID= "98171997455"
  FIREBASE_APPID= "1:98171997455:web:aee71235655f4212fcc27a"
  FIREBASE_MEASUREMENTID= "G-Z8R8M1LRVE"
  FIREBASE_DATABASE_URL= "https://triviachatapp-default-rtdb.firebaseio.com/"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
